<?php
/**
 * @file
 * Define modules hooks.
 */

/**
 * Implements hook_menu().
 */
function ding_redia_variables_menu() {
  $items = array();

  $items['redia/variables'] = array(
    'title' => 'Display variables as JSON output',
    'access callback' => TRUE,
    'delivery callback' => 'drupal_json_output',
    'page callback' => 'ding_redia_variables_display',
  );

  return $items;
}

/**
 * Provide variables to the json output.
 *
 * @return array
 *   List of all variables to the output.
 */
function ding_redia_variables_display() {
  // TODO: Find a way to remove hardcode.
  $carousels = array(
    'carousel',
    'ding_item_viewer',
  );
  $carousel_configs = array();
  foreach ($carousels as $carousel) {
    $carousel_configs[] = _ding_redia_variables_get_carousel_configs($carousel);
  }

  $variables = array(
    'dibs_settings_ding_dibs_1',
    'ting_search_profile',
    'ting_search_results_per_page',
    'ting_search_result_message_limit',
    'ting_search_url',
    'ting_sort_default',
    'ting_ranking_custom',
    'ting_ranking_fields',
    'ting_boost_fields',
    'ting_agency',
    'ting_carousel_search_queries',
  );
  $variables_configs = array();
  foreach ($variables as $variable) {
    $variables_configs[$variable] = variable_get($variable, '');
  }

  return array(
    'variables' => $variables_configs,
    'carousels' => $carousel_configs,
  );
}

/**
 * Get panels configurations.
 *
 * @return array
 *   List of carousels pane configurations.
 */
function _ding_redia_variables_get_carousel_configs($carousel) {
  $query = db_select('panels_pane', 'pp');
  $result = $query
    ->fields('pp', array('subtype', 'configuration'))
    ->condition('subtype', $carousel)
    ->execute()
    ->fetchAll();

  $carousels = array();
  foreach ($result as $settings) {
  $configs = unserialize($settings->configuration);
    $carousels[] = array(
      'name' => $carousel,
      'configs' => $configs['searches'],
    );
  }

  return $carousels;
}
